### ISSUE TITLE
Always use forward slashes, even on Windows?

### ISSUE THREAD

**Issue by belluzj** [LettError/designSpaceDocument#22]
Hello,

I'm using MutatotMath on Windows and the [line 217 of document.py](https://github.com/LettError/MutatorMath/blob/master/Lib/mutatorMath/ufo/document.py#L217) uses `os.path`, so it always replaces forward slashes with backward slashes on Windows. There might be an issue if someone generates a design space document on windows and tries to use it on linux/mac, so maybe the spec could be updated to say that the `filename` attribute should always use forward slashes; by adding a bullet point to this list:

https://github.com/LettError/designSpaceDocument/blob/master/README.md#paths-and-filenames

What do you think?

@moyogo

**Comment by anthrotype** [comment]
I agree it's better to normalize this and always use forward slashes for path names in the designspace.
I think relative paths with forward slashes should work on Windows as well.

**Comment by belluzj** [comment]
OK, I will open a pull request here and in MutatorMath.
