### ISSUE TITLE
a way to specify "hidden" axis for fvar?

### ISSUE THREAD

**Issue by anthrotype** [LettError/designSpaceDocument#24]
in fvar table, VariationAxisRecords can have an optional `HIDDEN_FLAG` to specify whether it should be exposed directly in user interfaces.

https://www.microsoft.com/typography/otspec/fvar.htm

Should designspace axis elements have an optional `flags` attribute containing the hex string of the bit mask, e.g. "0x01"?
Or alternatively, a `hidden="1"` attribute? ("1" means True, no attribute implies False).

**Comment by davelab6** [comment]
Bit masks seems errorprone, I'd prefer a binary attribute value

**Comment by yarmola** [comment]
is there a decision about it?

**Comment by anthrotype** [comment]
`hidden=1` would be my preferred choice.
I think it's ok to have optional attributes that are only used by either mutatorMath or varLib (in this case this would only be used by the latter).

/cc @LettError @behdad

**Comment by LettError** [comment]
No objection to hidden="1". Would that eliminate the need for bitmasks?

**Comment by anthrotype** [comment]
yeah, either one or the other. That's currently the only flag allowed. If we added a flags attribute with an hex string, we wouldn't need to change the spec when another flag is added (if ever). But hidden is more human-readable.

**Comment by LettError** [comment]
I'm willing to take that risk for the sake of clarity.

**Comment by moyogo** [comment]
Clarity is better.

**Comment by LettError** [comment]
`hidden` attribute added to axis element, object, reader, writer. https://github.com/LettError/designSpaceDocument/commit/ff4705554c1eb6166c5ea41a7f5f9ed53eba6036

**Comment by anthrotype** [comment]
Thanks Erik! I'm going to implement that in varLib
